spring.application.name: boxfish-online-invitation

logging:
  file: ${user.home}/logs/${spring.application.name}.log
  level:
    org.springframework: INFO
    com.boxfishedu.online.invitation: DEBUG
    tk.mybatis: DEBUG

server.port: 8198

conf.accounts:
  - userId: 1001
    role: admin
    username: creator
    password: 1234
  - userId: 1002
    role: user
    username: onlooker
    password: 5687

spring.profiles.active: testm
---
spring:
  profiles: development

  datasource:
    url: jdbc:mysql://boxfish2016outside.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf8
    username: mall
    password: Box123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
---
spring:
  profiles: sandbox

  datasource:
    url: jdbc:mysql://boxfish2016inside.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf8
    username: mall
    password: Box123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
      host: 8619f2f4a93c4a70.m.cnbja.kvstore.aliyuncs.com
      password: Box12345678
      database: 5
      timeout: 5000
---
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://boxfish2016inside.mysql.rds.aliyuncs.com:3306/mall_test?useUnicode=true&characterEncoding=utf8
    username: mall
    password: Box123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
      host: 8619f2f4a93c4a70.m.cnbja.kvstore.aliyuncs.com
      password: Box12345678
      database: 12

---
spring:
  profiles: testm

  datasource:
      url: jdbc:mysql://192.168.0.100:3306/mall_sylvia?useUnicode=true&characterEncoding=utf8
      username: root
      password: boxfish
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  redis:
      host: localhost