spring.application.name: boxfish-online-order

logging.file: ${user.home}/logs/${spring.application.name}.log
logging.level:
    org.springframework: INFO
    com.boxfishedu: DEBUG
    tk.mybatis: DEBUG

permission_host: http://base.boxfish.cn/passbook/user/me?access_token=
payment-key: boxfish2016
conf.benchmark.score: 100000

spring.jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization-inclusion: always
    time-zone: GMT+8

spring.datasource:
    test-while-idle: true
    validation-query: SELECT 1
    connection-timeout: 5000
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 2
    max-active: 50
    max-idle: 20

#spring.jpa:
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    show-sql: false

server.port: 8082

spring.profiles.active: local

---
spring.profiles: local

spring.datasource:
    url: jdbc:mysql://192.168.0.100:3306/mall_sylvia?useUnicode=true&characterEncoding=utf8
    username: root
    password: boxfish
spring.rabbitmq:
    host: 192.168.77.91
    port: 5672
    username: boxfish
    password: boxfish
    virtualHost: local
#spring.jpa:
#    show-sql: true
payment-host: http://192.168.55.237:8080
product-host: http://127.0.0.1:8081
edu-center-host: http://101.201.239.116:8080
invitation-host: http://127.0.0.1:8091/invitation-check
---
spring.profiles: development
spring.datasource:
    url: jdbc:mysql://boxfish2016inside.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf8
    username: mall
    password: Box123456
    driver-class-name: com.mysql.jdbc.Driver
spring.rabbitmq:
    host: 192.168.77.91
    port: 5672
    username: boxfish
    password: boxfish
    virtualHost: local
spring.redis:
    host: 8619f2f4a93c4a70.m.cnbja.kvstore.aliyuncs.com
    password: Box12345678
    database: 10
payment-host: http://101.201.237.252:8888
product-host: http://127.0.0.1:8081
edu-center-host: http://101.201.239.116:8080
permission_host: http://114.55.58.184:8099/user/me?access_token=
invitation-host: http://127.0.0.1:8091/invitation-check
---
spring.profiles: test

spring.datasource:
    url: jdbc:mysql://boxfish2016inside.mysql.rds.aliyuncs.com:3306/mall_test?useUnicode=true&characterEncoding=utf8
    username: mall
    password: Box123456
spring.rabbitmq:
    host: 192.168.77.91
    port: 5672
    username: admin
    password: boxfish123
    virtualHost: local
spring.redis:
    host: 8619f2f4a93c4a70.m.cnbja.kvstore.aliyuncs.com
    password: Box12345678
    database: 10
product-host: http://127.0.0.1:8081
payment-host: http://123.56.6.91:8888
edu-center-host: http://127.0.0.1:8080
invitation-host: http://127.0.0.1:8091/invitation-check
permission_host: http://114.55.58.184:8099/user/me?access_token=

---
spring.profiles: production.private
spring.application.name: boxfish-online-order-private

spring.datasource:
    url: jdbc:mysql://boxfish-online-2016-inside.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf8
    username: mall
    password: gTNTnccWVA3oDEF6qWFgeDBxsYxuGgzC
spring.redis:
    host: 96cbdee519414aba.m.cnhza.kvstore.aliyuncs.com
    password: kVxowYcWE6NdfKAP6zDhxZsZgkPGuC
    database: 3
spring.jackson:
    serialization-inclusion: non_null
spring.rabbitmq:
    addresses: 192.168.1.17,192.168.1.18,192.168.1.19
    port: 5672
    username: admin
    password: boxfish123
    virtualHost: local

server.port: 8083

edu-center-host: http://online-api.boxfish.cn/fishcard
product-host: http://online-api.boxfish.cn
payment-host: https://pay.boxfish.cn
invitation-host: http://online-api.inside.boxfish.cn/invitation-check

---
spring.profiles: production.public
spring.application.name: boxfish-online-order-public

spring.datasource:
    url: jdbc:mysql://boxfish-online-2016-inside.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf8
    username: mall
    password: gTNTnccWVA3oDEF6qWFgeDBxsYxuGgzC
spring.redis:
    host: 96cbdee519414aba.m.cnhza.kvstore.aliyuncs.com
    password: kVxowYcWE6NdfKAP6zDhxZsZgkPGuC
    database: 2
spring.jackson:
    serialization-inclusion: non_null
spring.rabbitmq:
    addresses: 192.168.1.17,192.168.1.18,192.168.1.19
    port: 5672
    username: admin
    password: boxfish123
    virtualHost: local

server.port: 8082

edu-center-host: http://online-api.boxfish.cn/fishcard
product-host: http://online-api.boxfish.cn
payment-host: https://pay.boxfish.cn
invitation-host: http://online-api.inside.boxfish.cn/invitation-check

